### ISSUE TITLE
Meshviewer 

### ISSUE THREAD

**Issue by tc-maxx** [Freifunk-Greifswald/UniFi.php#1]
Hallo,

ich versuche den Meshviewer mit den generierten JSON-Files zum laufen zu bekommen, bisher aber ohne Erfolg.

Kannst du sagen, welche Version des Meshviewers du verwendest?

**Comment by schlady** [comment]
Wir nutzen https://github.com/ffrgb/meshviewer

**Comment by BrunoRobert** [comment]
Richte am besten einen separaten Nutzer im UniFi-Controller mit Nur-Lese-Rechten ein und trage die Zugangsdaten in Zeile 8 ein.
